// Generated by CoffeeScript 1.8.0
(function() {
  var CollectionTab, Tab,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tab = require('./tab');

  CollectionTab = (function(_super) {
    __extends(CollectionTab, _super);

    function CollectionTab(children, delim) {
      this.children = children;
      this.delim = delim;
    }

    CollectionTab.prototype.depth = function() {
      var child, depths;
      depths = (function() {
        var _i, _len, _ref, _results;
        _ref = this.children;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          if (child instanceof Tab) {
            _results.push(child.depth());
          } else {
            _results.push(1);
          }
        }
        return _results;
      }).call(this);
      return 1 + Math.max.apply(Math, depths);
    };

    CollectionTab.prototype._oneLine = function(buffer, level) {
      this._oneLineOpen(buffer, level);
      this._oneLineChildren(buffer, level + 1);
      return this._oneLineClose(buffer, level);
    };

    CollectionTab.prototype._oneLineChildren = function(buffer, level) {
      var child, i, _i, _len, _ref, _results;
      _ref = this.children;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        _results.push(this._oneLineChild(buffer, level + 1, child, i));
      }
      return _results;
    };

    CollectionTab.prototype._oneLineChild = function(buffer, level, child, i) {
      this._oneLineChildTab(buffer, level, i);
      child.oneLine(buffer, level);
      return this._oneLineDelim(buffer, level, i);
    };

    CollectionTab.prototype._oneLineChildTab = function(buffer, level, i) {
      return buffer.pushOneLine(' ');
    };

    CollectionTab.prototype._oneLineDelim = function(buffer, level, i) {
      if (i < this.children.length - 1) {
        return buffer.pushOneLine(this.delim);
      }
    };

    CollectionTab.prototype._multiLine = function(buffer, level) {
      this._multiLineOpen(buffer, level);
      this._multiLineChildren(buffer, level);
      return this._multiLineClose(buffer, level);
    };

    CollectionTab.prototype._multiLineChildren = function(buffer, level) {
      var child, i, _i, _len, _ref, _results;
      _ref = this.children;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        _results.push(this._multiLineChild(buffer, level + 1, child, i));
      }
      return _results;
    };

    CollectionTab.prototype._multiLineChild = function(buffer, level, child, i) {
      this._multiLineChildTab(buffer, level, i);
      child.multiLine(buffer, level);
      return this._multiLineDelim(buffer, level, i);
    };

    CollectionTab.prototype._multiLineChildTab = function(buffer, level, i) {
      return buffer.fixedTab(level);
    };

    CollectionTab.prototype._multiLineDelim = function(buffer, level, i) {
      if (i < this.children.length - 1) {
        return buffer.push(this.delim);
      }
    };

    return CollectionTab;

  })(Tab);

  module.exports = CollectionTab;

}).call(this);
