// Generated by CoffeeScript 1.10.0
(function() {
  var Buffer, Collection, KeyVal, Literal, Tab, makePrinter, prettify;

  Buffer = require('./buffer');

  Tab = require('./tab');

  Collection = require('./collection');

  KeyVal = require('./keyval');

  Literal = require('./literal');

  prettify = function(obj, converter) {
    var buffer, converted;
    converted = converter.convert(obj);
    buffer = new Buffer(80);
    converted.multiLine(buffer, 0);
    return buffer.join();
  };

  makePrinter = function(converter) {
    return function(obj) {
      return prettify(obj, converter);
    };
  };

  module.exports = {
    makePrinter: makePrinter,
    prettify: prettify,
    Buffer: Buffer,
    Tab: Tab,
    Collection: Collection,
    Literal: Literal,
    KeyVal: KeyVal
  };

}).call(this);
