// Generated by CoffeeScript 1.10.0
(function() {
  var Tab;

  Tab = (function() {
    function Tab() {}

    Tab.prototype.depth = function() {
      return 1;
    };

    Tab.prototype.oneLine = function(buffer, level) {
      var temp;
      temp = buffer.branch();
      this._oneLine(temp, level);
      return buffer.merge(temp);
    };

    Tab.prototype.multiLine = function(buffer, level) {
      var e, error;
      try {
        return this.oneLine(buffer, level);
      } catch (error) {
        e = error;
        return this._multiLine(buffer, level);
      }
    };

    return Tab;

  })();

  module.exports = Tab;

}).call(this);
